config/routes.rb
Rails.application.routes.draw do
  get 'modules/index'

  get 'modules/show'

  resources :reports
  get 'index/apps'

  root 'static_pages#home'

  get 'static_pages/about'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/report.rb
class Report < ApplicationRecord
  has_many :report_details
end

app/models/report_detail.rb
class ReportDetail < ApplicationRecord
  belongs_to :report

  serialize :data, Hash
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :get_reports
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
   
  private
    def get_reports
      @reports = Report.all
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  
end

app/controllers/modules_controller.rb
class ModulesController < ApplicationController
  def index
  end

  def show
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:desc, :sql)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/modules_helper.rb
module ModulesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/index/apps.html.erb
<h1>Index#apps</h1>
<p>Find me in app/views/index/apps.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DPT - DeltaProjectsTools</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<%= render 'static_pages/header' %>
<body>
<div class="container">
  <%= yield %>  
</div>
</body>
<%= render 'static_pages/footer' %>
</html>

app/views/modules/index.html.erb
<h1>Modules#index</h1>
<p>Find me in app/views/modules/index.html.erb</p>

app/views/modules/show.html.erb
<h1>Modules#show</h1>
<p>Find me in app/views/modules/show.html.erb</p>

app/views/reports/_form.html.erb
<%= form_for(report) do |f| %>
  <% if report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :desc %>
    <%= f.text_field :desc %>
  </div>

  <div class="field">
    <%= f.label :sql %>
    <%= f.text_field :sql %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.desc %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form', report: @report %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Desc:</strong>
  <%= @report.desc %>
</p>

<p>
  <strong>Sql:</strong>
  <%= @report.sql %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>

app/views/static_pages/_footer.html.erb
<footer>
    <p>
        Copyrigth (c) 2017 DC
    </p>
</footer>

app/views/static_pages/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
<nav data-turbolinks="false" role="navigation">
  <div class="container">

    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'DPT - DeltaProjectsTools', root_path, class:'navbar-brand' %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        
        <li class="dropdown">
          <a data-target="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              Moduły<span class="caret"></span>
          </a>
          <ul class="dropdown-menu">
            <% @reports.each do |report| %>
              <li><a><%= report.desc %> </a></li>
            <% end %>
<!--
            <li><a data-target="#">ING_BARCODE_ABI</a></li>
            <li><a data-target="#">2</a></li>
            <li><a data-target="#">3</a></li> -->
          </ul>
        
        <li><%= link_to 'Pomoc', static_pages_about_path %></li>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
</header>

app/views/static_pages/about.html.erb
<div class="jumbotron">
    <h1>StaticPages#about</h1>
    <p>Find me in app/views/static_pages/about.html.erb</p>
</div>

app/views/static_pages/home.html.erb
<div class="jumbotron">
    <h1>StaticPages#home</h1>
    <p>Find me in app/views/static_pages/home.html.erb</p>
    <p>Buziaczki dla Wioli</p>
</div>